# Generated by Django 4.1.5 on 2024-06-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_course_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golfcourse',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='golfcoursegroup',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
