# Generated by Django 4.1.5 on 2025-06-29 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('golf_course_service', '0002_alter_golfcourse_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfcourse',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='golfcoursegroup',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.customer'),
            preserve_default=False,
        ),
    ]
