# Generated by Django 4.1.5 on 2024-06-08 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_course_service', '0002_rename_customer_id_golfcourse_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfcoursegroup',
            name='golf_courses',
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='golf_course_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='golf_course_service.golfcoursegroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='golfcourse',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='golf_course_service.customer'),
        ),
        migrations.AlterField(
            model_name='golfcoursegroup',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='golf_course_service.customer'),
        ),
    ]
