# Generated by Django 4.1.5 on 2024-06-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_course_service', '0003_remove_golfcoursegroup_golf_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcoursegroup',
            name='name',
            field=models.CharField(default='default_name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golfcoursegroup',
            name='street_address',
            field=models.CharField(default='default address', max_length=50),
            preserve_default=False,
        ),
    ]
