# Generated by Django 4.1.5 on 2024-06-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_course_service', '0004_golfcoursegroup_name_golfcoursegroup_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcoursegroup',
            name='state',
            field=models.CharField(default='CO', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golfcoursegroup',
            name='zip_code',
            field=models.CharField(default='80127', max_length=5),
            preserve_default=False,
        ),
    ]
