# Generated by Django 4.1.5 on 2024-06-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_course_service', '0005_golfcoursegroup_state_golfcoursegroup_zip_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golfcoursegroup',
            options={'verbose_name': 'GolfCourseGroup'},
        ),
        migrations.AlterModelTable(
            name='golfcourse',
            table='GOLF_COURSE',
        ),
        migrations.AlterModelTable(
            name='golfcoursegroup',
            table='GOLF_COURSE_GROUP',
        ),
    ]
