# Generated by Django 4.1.5 on 2024-06-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_course_service', '0006_alter_golfcoursegroup_options_alter_golfcourse_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer'},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='CUSTOMER',
        ),
    ]
