# Generated by Django 4.1.5 on 2024-10-13 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('golf_course_service', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeeSheetSettings',
            fields=[
                ('tee_sheet_settings_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.DurationField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('number_of_slots', models.PositiveIntegerField(default=4)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alternative_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('alternative_price_timespan', models.DurationField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('golf_course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='golf_course_service.golfcourse')),
            ],
            options={
                'verbose_name': 'TeeSheetSettings',
                'db_table': 'TEE_SHEET_SETTINGS',
            },
        ),
        migrations.CreateModel(
            name='TeeSheetTime',
            fields=[
                ('tee_sheet_time_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('golf_course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='golf_course_service.golfcourse')),
                ('tee_sheet_settings', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tee_sheet_service.teesheetsettings')),
            ],
            options={
                'verbose_name': 'TeeSheetTime',
                'db_table': 'TEE_SHEET_TIME',
            },
        ),
        migrations.CreateModel(
            name='TeeTimeSlot',
            fields=[
                ('tee_time_slot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Booked'), (3, 'On_Hold')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('tee_sheet_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tee_sheet_service.teesheettime')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='user_profile.userprofile')),
            ],
            options={
                'verbose_name': 'TeeTimeSlots',
                'db_table': 'TEE_TIME_SLOT',
            },
        ),
    ]
