# Generated by Django 4.1.5 on 2024-06-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_course_service', '0005_golfcoursegroup_state_golfcoursegroup_zip_code'),
        ('user_profile', '0005_rename_customer_id_userprofile_customer'),
        ('tee_sheet_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tee_sheet_settings',
            new_name='TeeSheetSettings',
        ),
        migrations.RenameModel(
            old_name='tee_sheet_time',
            new_name='TeeSheetTime',
        ),
        migrations.RenameModel(
            old_name='tee_time_slot',
            new_name='TeeTimeSlot',
        ),
    ]
