# Generated by Django 4.1.5 on 2024-06-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tee_sheet_service', '0002_rename_tee_sheet_settings_teesheetsettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teesheetsettings',
            options={'verbose_name': 'TeeSheetSettings'},
        ),
        migrations.AlterModelOptions(
            name='teesheettime',
            options={'verbose_name': 'TeeSheetTime'},
        ),
        migrations.AlterModelOptions(
            name='teetimeslot',
            options={'verbose_name': 'TeeTimeSlots'},
        ),
        migrations.AlterModelTable(
            name='teesheetsettings',
            table='TEE_SHEET_SETTINGS',
        ),
        migrations.AlterModelTable(
            name='teesheettime',
            table='TEE_SHEET_TIME',
        ),
        migrations.AlterModelTable(
            name='teetimeslot',
            table='TEE_TIME_SLOT',
        ),
    ]
