# Generated by Django 4.1.5 on 2024-06-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_userprofile_options_alter_userprofile_table'),
        ('tee_sheet_service', '0003_alter_teesheetsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teetimeslot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='user_profile.userprofile'),
        ),
    ]
