# Generated by Django 4.2.1 on 2023-11-19 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                ("events_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("requested_for_user_id", models.CharField(max_length=30)),
                ("event_date_time", models.DateTimeField()),
                ("event_type", models.CharField(max_length=30)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_last_updated", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField()),
                (
                    "requested_by_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Events", "ordering": ("date_created",),},
        ),
        migrations.CreateModel(
            name="LessonRequest",
            fields=[
                (
                    "lesson_request_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("requested_datetime", models.DateTimeField()),
                ("date_created", models.DateTimeField()),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Requested"), (2, "Accepted"), (3, "Denied")],
                        default=1,
                    ),
                ),
                (
                    "instructor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.instructor",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventStudent",
            fields=[
                (
                    "event_student_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventcalendar.events",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventInstructor",
            fields=[
                (
                    "event_instructor_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventcalendar.events",
                    ),
                ),
                (
                    "instructor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.instructor",
                    ),
                ),
            ],
        ),
    ]
