# Generated by Django 4.2.1 on 2023-05-31 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_for_user_id", models.CharField(max_length=30)),
                ("event_date_time", models.DateTimeField()),
                ("event_type", models.CharField(max_length=30)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_last_updated", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField()),
                (
                    "requested_by_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Events", "ordering": ("date_created",),},
        ),
    ]
