# Generated by Django 4.2.1 on 2023-06-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventcalendar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
