# Generated by Django 4.2.1 on 2023-11-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventcalendar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events", name="active", field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="events",
            name="event_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Lesson"), (2, "Unavailable")], default=1
            ),
        ),
    ]
