# Generated by Django 4.2.1 on 2023-11-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventcalendar", "0002_alter_events_active_alter_events_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonrequest",
            name="lesson_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lessonrequest",
            name="lesson_duration",
            field=models.DurationField(default="60 minutes"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lessonrequest",
            name="lesson_type",
            field=models.CharField(default="Golf", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lessonrequest",
            name="notes",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="lessonrequest",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
