# Generated by Django 4.1.5 on 2024-04-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_instructor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorstudent',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructorstudent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='InstructorStudent',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
