# Generated by Django 4.1.5 on 2024-06-02 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_course_service', '0001_initial'),
        ('user_profile', '0003_remove_instructorstudent_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf_course_service.customer'),
        ),
    ]
