# Generated by Django 4.1.5 on 2024-06-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
