# Generated by Django 4.1.5 on 2024-06-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_rename_customer_id_userprofile_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'UserProfile'},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='USER_PROFILE',
        ),
    ]
