# Generated by Django 4.2.1 on 2023-05-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="myuser", name="credits",),
        migrations.RemoveField(model_name="myuser", name="linkedin_token",),
    ]
