# Generated by Django 4.2.1 on 2023-06-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_myuser_credits_remove_myuser_linkedin_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="myuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
