# Generated by Django 4.2.1 on 2023-08-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_myuser_first_name_myuser_last_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="myuser", name="first_name",),
        migrations.RemoveField(model_name="myuser", name="last_name",),
    ]
