# Generated by Django 4.1.5 on 2025-06-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('tenant_admin', 'Tenant Administrator'), ('tenant_user', 'Tenant User'), ('platform_admin', 'Platform Administrator'), ('support_staff', 'Support Staff'), ('public_user', 'Public User')], default='public_user', max_length=20),
        ),
    ]
