# Generated by Django 4.1.5 on 2025-06-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_last_updated',
        ),
    ]
